FROM almalinux:latest
# CMD ["ping", "google.com"]
CMD [ "google.com" ]

#CMD can be overridden at runtime
#ENTRYPOINT cant be overridden like CMD, If we try It will be append to the entrypoint
#For better practice Use CMD to provide default arguments to the ENTRYPOINT.

ENTRYPOINT [ "ping" ]