version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: 6ce72e408174
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: d3b54ae9be4d
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: d8ef4ceef2ef
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend